spring.application.name=blss-lab

spring.jta.enabled=true

app.datasource.db1.url=jdbc:postgresql://localhost:5432/blss_db1
app.datasource.db1.username=postgres
app.datasource.db1.password=postgres

app.datasource.db2.url=jdbc:postgresql://localhost:5432/blss_db2
app.datasource.db2.username=postgres
app.datasource.db2.password=postgres

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

jwt.sign.key=JKWFBVUWEHBCUFBEWUCBOUEWBCUQEBDCUOBWDOUCBWNWEBO
users.xml.path=./src/main/resources/users.xml