spring.application.name=blss-lab

spring.jta.enabled=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
rabbitmq.connection.housing.queue=moderation.housing.queue

server.port=8081