spring.application.name=api-core

spring.jta.enabled=true

app.datasource.postgres.url=jdbc:postgresql://localhost:5433/blss
app.datasource.postgres.username=postgres
app.datasource.postgres.password=postgres

app.datasource.mysql.url=jdbc:mysql://localhost:3307/blss
app.datasource.mysql.username=root
app.datasource.mysql.password=root

spring.jpa.show-sql=true

jwt.sign.key=JKWFBVUWEHBCUFBEWUCBOUEWBCUQEBDCUOBWDOUCBWNWEBO
users.xml.path=./src/main/resources/users.xml

server.port=8080